version: "3.9"

services:
  postgres:
    container_name: db-postgres-go
    # image: "postgres:15.4-alpine"
    image: "ankane/pgvector" # This docker image with postgres@15.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go-project-local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
